{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testrbac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "testrbac.serviceAccountName" .  }}@{{ .Values.projectId }}.iam.gserviceaccount.com
{{- end -}}